# Generated by Django 2.2.12 on 2023-05-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='medias/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
