# Generated by Django 4.2.1 on 2023-05-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0002_alter_video_id_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='User', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='User', max_length=30),
            preserve_default=False,
        ),
    ]
