# Generated by Django 4.2.1 on 2023-05-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0004_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
    ]
