# Generated by Django 4.2.1 on 2023-06-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0012_alter_profile_picture_alter_video_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='avatar',
            field=models.ImageField(default='avatar1', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='text',
            field=models.CharField(default='text', max_length=3000),
            preserve_default=False,
        ),
    ]
